//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKPICaNhan
    {
        public Nullable<double> TrongSo { get; set; }
        public string NguonChungMinh { get; set; }
        public string KeHoach { get; set; }
        public string ThucHien { get; set; }
        public Nullable<double> HoanThanh { get; set; }
        public int ChitietID { get; set; }
    
        public virtual PhongKhoa PhongKhoa { get; set; }
        public virtual ChiTietTieuChiMucTieuCaNhan ChiTietTieuChiMucTieuCaNhan { get; set; }
    }
}
