//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTieuChiMucTieuCaNhan
    {
        public int MaChiTietMucTieuCN { get; set; }
        public Nullable<int> TrongSoKPIHT { get; set; }
        public Nullable<int> MaKPI { get; set; }
        public Nullable<int> ChiTieuHT { get; set; }
    
        public virtual ChiTietKPICaNhan ChiTietKPICaNhan { get; set; }
    }
}
