//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKPICaNhan
    {
        public string MaPhieuKPICN { get; set; }
        public int MaKPI { get; set; }
        public string ChiTieuKPICN { get; set; }
        public Nullable<double> TrongSoTCCN { get; set; }
        public Nullable<double> TrongSoKPICN { get; set; }
        public Nullable<int> KPICaNhanDangKyThem { get; set; }
        public Nullable<double> TrongSoKPICaNhanDangKyThem { get; set; }
        public string NguonChungMinh { get; set; }
        public string KeHoach { get; set; }
        public Nullable<double> ThucHien { get; set; }
        public Nullable<double> TyLeHoanThanh { get; set; }
        public Nullable<System.DateTime> ThoiDiemGhiNhan { get; set; }
        public string TieuChiDanhGiaKQ { get; set; }
        public Nullable<double> KetQua { get; set; }
        public Nullable<double> KetQuaKPIBV { get; set; }
        public Nullable<double> KetQuaKPIKP { get; set; }
        public Nullable<double> KetQuaKPIKPGiaTriCotLoiBV { get; set; }
    
        public virtual KPI KPI { get; set; }
        public virtual KPI KPI1 { get; set; }
        public virtual KPI_CaNhan KPI_CaNhan { get; set; }
    }
}
