//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKPICaNhan
    {
        public string MaPhieuKPICN { get; set; }
        public Nullable<double> TrongSoKPICN { get; set; }
        public string NguonChungMinh { get; set; }
        public string KeHoach { get; set; }
        public Nullable<double> ThucHien { get; set; }
        public Nullable<double> TyLeHoanThanh { get; set; }
        public Nullable<double> KetQua { get; set; }
        public Nullable<double> KetQuaKPIBV { get; set; }
        public Nullable<double> KetQuaKPIKP { get; set; }
        public Nullable<double> KetQuaKPIKPGiaTriCotLoiBV { get; set; }
        public string TieuChiDanhGiaKQ { get; set; }
        public Nullable<int> MaKPI { get; set; }
        public Nullable<int> MaKPI_DKT { get; set; }
    
        public virtual KPI KPI { get; set; }
        public virtual KPI_CaNhan KPI_CaNhan { get; set; }
        public virtual KPI_DangKiThem KPI_DangKiThem { get; set; }
    }
}
