//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTieuChiPhieuPhongKhoa
    {
        public string MaPhieuKPI { get; set; }
        public int MaChiTietPK { get; set; }
        public int TieuChiID { get; set; }
        public double TrongSo { get; set; }
    
        public virtual ChiTietKPIKhoaPhong ChiTietKPIKhoaPhong { get; set; }
        public virtual KPI_KhoaPhong KPI_KhoaPhong { get; set; }
        public virtual NhomTieuChi NhomTieuChi { get; set; }
    }
}
