//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTieuChiPhieuCaNhan
    {
        public string MaPhieuKPI { get; set; }
        public int MaChiTietCN { get; set; }
        public int TieuChiID { get; set; }
        public double TrongSo { get; set; }
    
        public virtual ChiTietKPICaNhan ChiTietKPICaNhan { get; set; }
        public virtual KPI_CaNhan KPI_CaNhan { get; set; }
        public virtual NhomTieuChi NhomTieuChi { get; set; }
    }
}
