//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTieuChiMucTieuKhoaPhong
    {
        public string MaPhieuKPIKP { get; set; }
        public int MaKPI { get; set; }
        public Nullable<double> TrongSoTCKP { get; set; }
        public Nullable<double> TrongSoKPIKP { get; set; }
    
        public virtual KPI KPI { get; set; }
        public virtual KPI_KhoaPhong KPI_KhoaPhong { get; set; }
    }
}
