//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhsachBieuMau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhsachBieuMau()
        {
            this.KPI_BenhVien = new HashSet<KPI_BenhVien>();
            this.KPI_CaNhan = new HashSet<KPI_CaNhan>();
            this.KPI_KhoaPhong = new HashSet<KPI_KhoaPhong>();
            this.KPI_TruongKhoaPhong = new HashSet<KPI_TruongKhoaPhong>();
            this.TongHopBieuMauPhieuKPI = new HashSet<TongHopBieuMauPhieuKPI>();
            this.TongHopBieuMauPhieuKPI1 = new HashSet<TongHopBieuMauPhieuKPI>();
        }
    
        public int IDBieuMau { get; set; }
        public string MaBieuMau { get; set; }
        public string TenBieuMau { get; set; }
        public Nullable<int> MaCapDoKPIBenhVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_BenhVien> KPI_BenhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_KhoaPhong> KPI_KhoaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_TruongKhoaPhong> KPI_TruongKhoaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TongHopBieuMauPhieuKPI> TongHopBieuMauPhieuKPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TongHopBieuMauPhieuKPI> TongHopBieuMauPhieuKPI1 { get; set; }
    }
}
