//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_TruongKhoaPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPI_TruongKhoaPhong()
        {
            this.ChiTietKPITruongKhoaPhong = new HashSet<ChiTietKPITruongKhoaPhong>();
        }
    
        public string MaPhieuKPITKP { get; set; }
        public string MaPhieuKPIBV { get; set; }
        public string MaPhieuKPIKP { get; set; }
        public System.DateTime NgayLapPhieuKPITKP { get; set; }
        public int IDBieuMau { get; set; }
        public int QuyNam { get; set; }
        public string MaNV { get; set; }
        public Nullable<double> TongTrongSoMucTieuTKP { get; set; }
        public string TongTrongSoKetQuaTKP { get; set; }
        public string NguoiNhanTieuChiDDKKPI { get; set; }
        public Nullable<System.DateTime> NgayNhanTieuChiDDKKPI { get; set; }
        public string NguoiXemXetDDKKPI { get; set; }
        public Nullable<System.DateTime> NgayXemXetDDKKPI { get; set; }
        public string NguoiPheDuyetDDKKPI { get; set; }
        public Nullable<System.DateTime> NgayPheDuyetDDKKPI { get; set; }
        public string NguoiNhanTieuChiDKQKPI { get; set; }
        public Nullable<System.DateTime> NgayNhanTieuChiDKQKPI { get; set; }
        public string NguoiXemXetDKQKPI { get; set; }
        public Nullable<System.DateTime> NgayXemXetDKQKPI { get; set; }
        public string NguoiPheDuyetDKQKPI { get; set; }
        public Nullable<System.DateTime> NgayPheDuyetDKQKPI { get; set; }
        public Nullable<double> TongTrongSoTKPGiaTriCotLoiBV { get; set; }
        public Nullable<double> TongTrongSoTKPKetQuaCuaQuaTrinhDanhGia { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual DanhsachBieuMau DanhsachBieuMau { get; set; }
        public virtual KPI_BenhVien KPI_BenhVien { get; set; }
        public virtual KPI_KhoaPhong KPI_KhoaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKPITruongKhoaPhong> ChiTietKPITruongKhoaPhong { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
