//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_BenhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPI_BenhVien()
        {
            this.ChiTietKPIBenhVien = new HashSet<ChiTietKPIBenhVien>();
            this.ChiTietTieuChiMucTieuBV = new HashSet<ChiTietTieuChiMucTieuBV>();
            this.KPI_KhoaPhong = new HashSet<KPI_KhoaPhong>();
            this.KPI_TruongKhoaPhong = new HashSet<KPI_TruongKhoaPhong>();
        }
    
        public string MaPhieuKPIBV { get; set; }
        public int NamPhieu { get; set; }
        public Nullable<double> TongTrongSo { get; set; }
        public string NguoiLap { get; set; }
        public string NguoiPheDuyet { get; set; }
        public System.DateTime NgayLapPhieuKPIBV { get; set; }
        public Nullable<System.DateTime> NgayPheDuyet { get; set; }
        public int IDBieuMau { get; set; }
    
        public virtual DanhsachBieuMau DanhsachBieuMau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKPIBenhVien> ChiTietKPIBenhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTieuChiMucTieuBV> ChiTietTieuChiMucTieuBV { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_KhoaPhong> KPI_KhoaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_TruongKhoaPhong> KPI_TruongKhoaPhong { get; set; }
    }
}
