//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_CaNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPI_CaNhan()
        {
            this.ChiTietKPICaNhan = new HashSet<ChiTietKPICaNhan>();
        }
    
        public string MaPhieuKPICN { get; set; }
        public string MaPhieuKPIKP { get; set; }
        public string QuyTacUngXu { get; set; }
        public Nullable<double> TrongSoQuyTacUngXu { get; set; }
        public int IDBieuMau { get; set; }
        public string MaNV { get; set; }
        public int QuyNam { get; set; }
        public System.DateTime NgayLapPhieuKPICN { get; set; }
        public string NguoiNhanTieuChiDDKKPI { get; set; }
        public Nullable<System.DateTime> NgayNhanTieuChiDDKKPI { get; set; }
        public string NguoiXemXetDDKKPI { get; set; }
        public Nullable<System.DateTime> NgayXemXetDDKKPI { get; set; }
        public string NguoiPheDuyetDDKKPI { get; set; }
        public Nullable<System.DateTime> NgayPheDuyetDDKKPI { get; set; }
        public string NguoiNhanTieuChiDKQKPI { get; set; }
        public Nullable<System.DateTime> NgayNhanTieuChiDKQKPI { get; set; }
        public string NguoiXemXetDKQKPI { get; set; }
        public Nullable<System.DateTime> NgayXemXetDKQKPI { get; set; }
        public string NguoiPheDuyetDKQKPI { get; set; }
        public Nullable<System.DateTime> NgayPheDuyetDKQKPI { get; set; }
        public Nullable<double> TongTrongSoCaNhan { get; set; }
        public Nullable<double> TongTrongSoCNMucTieuQuanTrongTrongNam { get; set; }
        public Nullable<double> TongTrongSoCNGiaTriCotLoiBV { get; set; }
        public Nullable<double> TongTrongSoCNKetQuaCuaQuaTrinhDanhGia { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual DanhsachBieuMau DanhsachBieuMau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKPICaNhan> ChiTietKPICaNhan { get; set; }
        public virtual KPI_KhoaPhong KPI_KhoaPhong { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual NguoiDung NguoiDung2 { get; set; }
        public virtual NguoiDung NguoiDung3 { get; set; }
        public virtual NguoiDung NguoiDung4 { get; set; }
        public virtual NguoiDung NguoiDung5 { get; set; }
        public virtual NguoiDung NguoiDung6 { get; set; }
        public virtual NguoiDung NguoiDung7 { get; set; }
    }
}
