//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_KhoaPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPI_KhoaPhong()
        {
            this.ChiTietTieuChiMucTieuKhoaPhong = new HashSet<ChiTietTieuChiMucTieuKhoaPhong>();
        }
    
        public string MaPhieuKPI { get; set; }
        public int IDChiTietKPIKP { get; set; }
        public int TrangThai { get; set; }
        public string MaPK { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> Quy { get; set; }
        public int IDBieuMau { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<bool> TruongPK { get; set; }
    
        public virtual ChiTietKPIKhoaPhong ChiTietKPIKhoaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTieuChiMucTieuKhoaPhong> ChiTietTieuChiMucTieuKhoaPhong { get; set; }
        public virtual DanhsachBieuMau DanhsachBieuMau { get; set; }
        public virtual PhongKhoa PhongKhoa { get; set; }
    }
}
