//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiTruyCap
    {
        public int Id { get; set; }
        public string MaNV { get; set; }
        public string TenNguoiTruyCap { get; set; }
        public string MaChucNang { get; set; }
        public bool QuyenTruyCap { get; set; }
        public string MaQuyen { get; set; }
    }
}
