//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.KPI_BenhVien = new HashSet<KPI_BenhVien>();
            this.KPI_BenhVien1 = new HashSet<KPI_BenhVien>();
            this.KPI_CaNhan = new HashSet<KPI_CaNhan>();
            this.KPI_CaNhan1 = new HashSet<KPI_CaNhan>();
            this.KPI_CaNhan2 = new HashSet<KPI_CaNhan>();
            this.KPI_CaNhan3 = new HashSet<KPI_CaNhan>();
            this.KPI_CaNhan4 = new HashSet<KPI_CaNhan>();
            this.KPI_CaNhan5 = new HashSet<KPI_CaNhan>();
            this.KPI_CaNhan6 = new HashSet<KPI_CaNhan>();
            this.KPI_CaNhan7 = new HashSet<KPI_CaNhan>();
            this.KPI_DangKiThem = new HashSet<KPI_DangKiThem>();
            this.KPI_KhoaPhong = new HashSet<KPI_KhoaPhong>();
            this.KPI_KhoaPhong1 = new HashSet<KPI_KhoaPhong>();
            this.KPI_KhoaPhong2 = new HashSet<KPI_KhoaPhong>();
            this.KPI_TruongKhoaPhong = new HashSet<KPI_TruongKhoaPhong>();
            this.ThongBao = new HashSet<ThongBao>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public byte[] HinhAnhNV { get; set; }
        public string SDT { get; set; }
        public string Gmail { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string MaPhongKhoa { get; set; }
        public string MaChucDanh { get; set; }
        public string MaQuyen { get; set; }
        public Nullable<int> MaCapDoKPIBenhVien { get; set; }
        public Nullable<bool> QuyenTruyCap { get; set; }
        public string MaChucNang { get; set; }
    
        public virtual ChucDanh ChucDanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_BenhVien> KPI_BenhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_BenhVien> KPI_BenhVien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_CaNhan> KPI_CaNhan7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_DangKiThem> KPI_DangKiThem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_KhoaPhong> KPI_KhoaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_KhoaPhong> KPI_KhoaPhong1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_KhoaPhong> KPI_KhoaPhong2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_TruongKhoaPhong> KPI_TruongKhoaPhong { get; set; }
        public virtual PhongKhoa PhongKhoa { get; set; }
        public virtual Quyen Quyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBao { get; set; }
    }
}
