//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKPITongHop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKPITongHop()
        {
            this.KPI_KhoaPhong = new HashSet<KPI_KhoaPhong>();
        }
    
        public string MaPhieuKPI { get; set; }
        public Nullable<int> MaKPI { get; set; }
        public string MaPK { get; set; }
        public Nullable<bool> TruongPK { get; set; }
        public Nullable<bool> CongViecCaNhan { get; set; }
        public string TieuChiID { get; set; }
        public Nullable<int> ChiTieuBV { get; set; }
        public Nullable<int> TrongSoTieuChiBV { get; set; }
        public Nullable<int> TrongSoKPIBV { get; set; }
        public Nullable<System.DateTime> NgayTaoPhieuKPI { get; set; }
    
        public virtual KPI KPI { get; set; }
        public virtual KPI_CaNhan KPI_CaNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_KhoaPhong> KPI_KhoaPhong { get; set; }
        public virtual PhongKhoa PhongKhoa { get; set; }
    }
}
