//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn_QuanLyKPI.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabBieuMau
    {
        public int IDBieuMau { get; set; }
        public string MaBieuMau { get; set; }
        public string TenBieuMau { get; set; }
        public Nullable<int> MaCapDoKPIBenhVien { get; set; }
    }
}
